// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/pear_data.go

// Package usecase is a generated GoMock package.
package usecase

import (
	presenter "api/domain/presenter"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPear is a mock of Pear interface.
type MockPear struct {
	ctrl     *gomock.Controller
	recorder *MockPearMockRecorder
}

// MockPearMockRecorder is the mock recorder for MockPear.
type MockPearMockRecorder struct {
	mock *MockPear
}

// NewMockPear creates a new mock instance.
func NewMockPear(ctrl *gomock.Controller) *MockPear {
	mock := &MockPear{ctrl: ctrl}
	mock.recorder = &MockPearMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPear) EXPECT() *MockPearMockRecorder {
	return m.recorder
}

// GetDataVersions mocks base method.
func (m *MockPear) GetDataVersions() ([]presenter.PearDataVersionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataVersions")
	ret0, _ := ret[0].([]presenter.PearDataVersionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataVersions indicates an expected call of GetDataVersions.
func (mr *MockPearMockRecorder) GetDataVersions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataVersions", reflect.TypeOf((*MockPear)(nil).GetDataVersions))
}
