// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/pear_data.go

// Package usecase is a generated GoMock package.
package usecase

import (
	entity "api/domain/entity"
	response "api/http/response"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPear is a mock of Pear interface.
type MockPear struct {
	ctrl     *gomock.Controller
	recorder *MockPearMockRecorder
}

// MockPearMockRecorder is the mock recorder for MockPear.
type MockPearMockRecorder struct {
	mock *MockPear
}

// NewMockPear creates a new mock instance.
func NewMockPear(ctrl *gomock.Controller) *MockPear {
	mock := &MockPear{ctrl: ctrl}
	mock.recorder = &MockPearMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPear) EXPECT() *MockPearMockRecorder {
	return m.recorder
}

// CreateData mocks base method.
func (m *MockPear) CreateData(db *gorm.DB, pearEntity entity.Pear, authorizationEntity entity.Authorization) (entity.Pear, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", db, pearEntity, authorizationEntity)
	ret0, _ := ret[0].(entity.Pear)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateData indicates an expected call of CreateData.
func (mr *MockPearMockRecorder) CreateData(db, pearEntity, authorizationEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockPear)(nil).CreateData), db, pearEntity, authorizationEntity)
}

// GetAdminDataVersions mocks base method.
func (m *MockPear) GetAdminDataVersions(db *gorm.DB) ([]response.PearAdminDataVersionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminDataVersions", db)
	ret0, _ := ret[0].([]response.PearAdminDataVersionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminDataVersions indicates an expected call of GetAdminDataVersions.
func (mr *MockPearMockRecorder) GetAdminDataVersions(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminDataVersions", reflect.TypeOf((*MockPear)(nil).GetAdminDataVersions), db)
}

// GetDataVersions mocks base method.
func (m *MockPear) GetDataVersions(db *gorm.DB) ([]response.PearDataVersionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataVersions", db)
	ret0, _ := ret[0].([]response.PearDataVersionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataVersions indicates an expected call of GetDataVersions.
func (mr *MockPearMockRecorder) GetDataVersions(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataVersions", reflect.TypeOf((*MockPear)(nil).GetDataVersions), db)
}

// UpdateAdminData mocks base method.
func (m *MockPear) UpdateAdminData(db *gorm.DB, pearEntity entity.Pear, authorizationEntity entity.Authorization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminData", db, pearEntity, authorizationEntity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminData indicates an expected call of UpdateAdminData.
func (mr *MockPearMockRecorder) UpdateAdminData(db, pearEntity, authorizationEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminData", reflect.TypeOf((*MockPear)(nil).UpdateAdminData), db, pearEntity, authorizationEntity)
}
