// Code generated by MockGen. DO NOT EDIT.
// Source: http/handler/auth.go

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// AdminSignup mocks base method.
func (m *MockAuth) AdminSignup(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminSignup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminSignup indicates an expected call of AdminSignup.
func (mr *MockAuthMockRecorder) AdminSignup(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminSignup", reflect.TypeOf((*MockAuth)(nil).AdminSignup), ctx)
}

// DownloadWithToken mocks base method.
func (m *MockAuth) DownloadWithToken(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadWithToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadWithToken indicates an expected call of DownloadWithToken.
func (mr *MockAuthMockRecorder) DownloadWithToken(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadWithToken", reflect.TypeOf((*MockAuth)(nil).DownloadWithToken), ctx)
}

// RegisterAdmin mocks base method.
func (m *MockAuth) RegisterAdmin(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAdmin", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAdmin indicates an expected call of RegisterAdmin.
func (mr *MockAuthMockRecorder) RegisterAdmin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAdmin", reflect.TypeOf((*MockAuth)(nil).RegisterAdmin), ctx)
}

// RequestEmail mocks base method.
func (m *MockAuth) RequestEmail(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmail", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestEmail indicates an expected call of RequestEmail.
func (mr *MockAuthMockRecorder) RequestEmail(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmail", reflect.TypeOf((*MockAuth)(nil).RequestEmail), ctx)
}
